### ISSUE TITLE
InvalidArgumentException using Symfony 3.3

### ISSUE THREAD

**Issue by bgatellier** [kbond/ZenstruckBackupBundle#12]
Hi,

Thanks for your work on this bundle :)

I would like to point out that I am not able to upgrade from Sf 3.2 to 3.3 because of the following error : 
`Uncaught exception 'Symfony\Component\DependencyInjection\Exception\InvalidArgumentException' with message 'Tag "<argument>" with type="service" has no or empty "id" attribute in "vendor/zenstruck/backup-bundle/src/DependencyInjection/../Resources/config/destinations.xml".' in vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php:484`

Have a good day!

**Comment by kbond** [comment]
@bgatellier thanks for noticing this - should be fixed in [v1.2.0](https://github.com/kbond/ZenstruckBackupBundle/releases/tag/v1.2.0)
