### ISSUE TITLE
Process timeout in ArchiveProcessor

### ISSUE THREAD

**Issue by kachkaev** [kbond/ZenstruckBackupBundle#9]
The website I was backing up using `ZenstruckBackupBundle` and `cron` suddenly stopped bringing in the new data. An investigation revealed an error, which is quite difficult to spot during testing.

Since the website data grows, it takes the `ArchiveProcessor` more time to generate a dump with the backup. At some point it may exceed the default 60-second timeout and crash.

What worked for me was adding `setTimeout(0)` to the `ProcessBuilder` in `ArchiveProcessor.php`. But I’m not sure this solution is safe enough to be advised to anyone.

``` php
        $process = ProcessBuilder::create(array($this->command, $this->options, $filename, './'))
            ->setWorkingDirectory($scratchDir)
            ->setTimeout(0) // <-----
            ->getProcess();
```

Another thing that might be needed is increasing the memory limit in PHP:

``` php
ini_set('memory_limit','2G');
```

If the bundle is not designed for large datasets, acknowledging the problem in `README.MD` may help other developers avoid not so pleasant surprises :–)

**Comment by kbond** [comment]
I am going to add a timeout option to `ArchiveProcessor`, `MySqlDumpSource` and `RsyncSource`.

For the memory limit, should I perhaps add an option in the run command?

**Comment by kachkaev** [comment]
Maybe just a warning about potentially exceeding the memory limit would be enough – I'm not sure. I haven’t seen any `ini_set` calls from the bundles yet and I don't know whether this is a good practice.

**Comment by kbond** [comment]
Your issue was the process timing out, not the memory limit, correct?

Yeah, I will just add a note to perhaps increase the memory_limit in your `app/console`.

**Comment by kachkaev** [comment]
It had both, to be honest. After I manually removed the timeout, I hit the `memory_limit` so had to fix that. I'll open another issue in a couple of minutes, which will give you a hint about what made my data grow so huge in the fist place :–)

Thank you for what you are doing and for responding to the comments so quickly!

**Comment by kbond** [comment]
Added the note here: 7f78801b5774d8c7bfdfebe1131332146e133185

**Comment by kbond** [comment]
Does #11 look good to you?

**Comment by kachkaev** [comment]
Yeah, all looks good! I'll let you know if I face any bugs with this new version. Thanks a lot!

**Comment by kbond** [comment]
No problem, I tagged a new release: https://github.com/kbond/ZenstruckBackupBundle/releases/tag/v1.1.0
